#!/bin/bash

# TRT Credentials Information Script
# Shows current system credentials for all boards

echo "═══════════════════════════════════════════════════════════════"
echo "           TRT YOCTO PROJECT - SYSTEM CREDENTIALS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔑 DEFAULT LOGIN CREDENTIALS (All Boards):"
echo "─────────────────────────────────────────────────────────────"
echo "Username: root"
echo "Password: 2020"
echo ""
echo "Username: developer"
echo "Password: 2020"
echo ""
echo "🌐 NETWORK ACCESS:"
echo "─────────────────────────────────────────────────────────────"
echo "SSH Access    : ssh root@192.168.100.10"
echo "Password      : 2020"
echo "Web Interface : http://192.168.100.10"
echo ""
echo "📡 PLATFORMS AFFECTED:"
echo "─────────────────────────────────────────────────────────────"
echo "✅ Raspberry Pi (raspberrypi-trt)"
echo "✅ BeagleBone Black/Industrial (beaglebone-trt)"  
echo "✅ NXP i.MX7 (imx7-trt)"
echo ""
echo "🔧 IMAGES AFFECTED:"
echo "─────────────────────────────────────────────────────────────"
echo "✅ trt-base-image"
echo "✅ trt-industrial-image"
echo "✅ trt-development-image"
echo "✅ trt-beaglebone-industrial"
echo ""
echo "⚠️  SECURITY NOTE:"
echo "─────────────────────────────────────────────────────────────"
echo "These are DEFAULT credentials for development."
echo "CHANGE THEM in production environments!"
echo ""
echo "To change credentials:"
echo "1. Edit: conf/trt-global.conf"
echo "2. Modify: TRT_ROOT_PASSWORD and TRT_DEVELOPER_PASSWORD"
echo "3. Rebuild images with: bitbake <image-name>"
echo ""
echo "═══════════════════════════════════════════════════════════════"